// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1Ugu4cykVBdYI4mRerAFenZytzjB-Pg',
    appId: '1:671584062848:web:bdcef3572a079eadbdc565',
    messagingSenderId: '671584062848',
    projectId: 'closetinventory',
    authDomain: 'closetinventory.firebaseapp.com',
    databaseURL: 'https://closetinventory-default-rtdb.firebaseio.com',
    storageBucket: 'closetinventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqFI5zcZ01jKwmWfm25zJpfAZf0kqZJg',
    appId: '1:671584062848:android:4a893adbc313fd3fbdc565',
    messagingSenderId: '671584062848',
    projectId: 'closetinventory',
    databaseURL: 'https://closetinventory-default-rtdb.firebaseio.com',
    storageBucket: 'closetinventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr1LyJNNcxZig7DQl5UWeOyjHg46vBmlA',
    appId: '1:671584062848:ios:cb0ffa8754aa703ebdc565',
    messagingSenderId: '671584062848',
    projectId: 'closetinventory',
    databaseURL: 'https://closetinventory-default-rtdb.firebaseio.com',
    storageBucket: 'closetinventory.firebasestorage.app',
    iosBundleId: 'com.example.closetinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr1LyJNNcxZig7DQl5UWeOyjHg46vBmlA',
    appId: '1:671584062848:ios:cb0ffa8754aa703ebdc565',
    messagingSenderId: '671584062848',
    projectId: 'closetinventory',
    databaseURL: 'https://closetinventory-default-rtdb.firebaseio.com',
    storageBucket: 'closetinventory.firebasestorage.app',
    iosBundleId: 'com.example.closetinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM1Ugu4cykVBdYI4mRerAFenZytzjB-Pg',
    appId: '1:671584062848:web:0028eeb2722d76c2bdc565',
    messagingSenderId: '671584062848',
    projectId: 'closetinventory',
    authDomain: 'closetinventory.firebaseapp.com',
    databaseURL: 'https://closetinventory-default-rtdb.firebaseio.com',
    storageBucket: 'closetinventory.firebasestorage.app',
  );

}